"""02_alter_urls_add_deleted.py

Revision ID: bc13732fb5eb
Revises: 538fa1c3773b
Create Date: 2023-02-18 00:39:44.657257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc13732fb5eb'
down_revision = '538fa1c3773b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'deleted')
    # ### end Alembic commands ###
